server:
  port: 50054

request:
  slow:
    percentage: 0.0
    latency: 0

  error:
    interval: 0

applicationTagsYamlFile: "./delivery/applicationTags.yaml"
wfReportingConfigYamlFile: "./wfReportingConfig.yaml"